# Configuraciones Base
font_family      Terminus (TTF)
font_size        14.0
foreground       #ffffff
background       #000000
disable_ligatures always
underline_hyperlinks never
background_opacity 0.85
window_padding_width 8

# Paleta de Colores - Búnker Crimson
selection_foreground  #000000
selection_background  #ff3333

# --- Colores ANSI Nitidos (Alto Contraste) ---
# Color 0 y 8 (Negro y Comentarios)
color0 #262626
color8 #b0b0b0

# Color 1 y 9 (Rojos)
color1 #ff4d4d
color9 #ff6666

# Color 2 y 10 (Verdes)
color2 #00e676
color10 #69ff94

# Color 3 y 11 (Amarillos)
color3 #ffeb3b
color11 #ffff72

# Color 4 y 12 (Azules)
color4 #40c4ff
color12 #80d8ff

# Color 5 y 13 (Magentas/Púrpuras)
color5 #e040fb
color13 #ea80fc

# Color 6 y 14 (Cianes)
color6 #00e5ff
color14 #18ffff

# Color 7 y 15 (Blancos)
color7 #e0e0e0
color15 #ffffff
